apiVersion: v1
kind: Namespace
metadata:
  name: fastapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: malharchikhale/fastapi-k8s:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: kube-config-n
          mountPath: /root/kube/config
          subPath: config
      volumes:
      - name: kube-config-n
        configMap:
          name: kube-config
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
