apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: prometheus  # Assuming Prometheus is deployed in the 'prometheus' namespace
spec:
  selector:
    app: prometheus  # Label selector to match your Prometheus deployment pods
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort  # Expose the service on a port on each Node
